spring.datasource.url=jdbc:postgresql://localhost:5432/production-optimizer
spring.datasource.username=postgres
spring.datasource.password=202418
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}